# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de requisitos al contenedor
COPY requirements.txt .

# Instala las dependencias
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# Copia el codigo de python al contenedor
COPY coctails_data.py .

# Define el comando por defecto para ejecutar la aplicación
CMD sleep 30 && python coctails_data.py